# Generated by Django 4.2.7 on 2023-12-21 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fullname', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('articulo_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('codigo_sku', models.CharField(max_length=25)),
                ('nombre_articulo', models.CharField(max_length=50)),
                ('factor_compra', models.PositiveIntegerField()),
                ('factor_reparto', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'articulos',
                'ordering': ['articulo_id'],
            },
        ),
        migrations.CreateModel(
            name='ArticulosBonificado',
            fields=[
                ('articulo_bonificado_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('codigo_sku', models.CharField(max_length=25)),
                ('nombre_articulo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'articulos_bonificado',
                'ordering': ['articulo_bonificado_id'],
            },
        ),
        migrations.CreateModel(
            name='CanalCliente',
            fields=[
                ('canal_cliente_id', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('canal_cliente_descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'canal_cliente',
                'ordering': ['canal_cliente_id'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nro_documento', models.CharField(max_length=12, unique=True)),
                ('nombre_razon_social', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('canal_cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.canalcliente')),
            ],
            options={
                'db_table': 'clientes',
                'ordering': ['cliente_id'],
            },
        ),
        migrations.CreateModel(
            name='CondicionesVenta',
            fields=[
                ('condicion_venta', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('genera_credito', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'condiciones_venta',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('empresa_id', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('nro_documento', models.CharField(max_length=11, unique=True)),
                ('razon_social', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='GruposProveedor',
            fields=[
                ('grupo_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('codigo_grupo', models.CharField(max_length=15)),
                ('grupo_descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.empresa')),
            ],
            options={
                'db_table': 'grupos_proveedor',
                'ordering': ['grupo_id'],
            },
        ),
        migrations.CreateModel(
            name='LineasArticulos',
            fields=[
                ('linea_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('codigo_linea', models.CharField(max_length=15)),
                ('linea_descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.gruposproveedor')),
            ],
            options={
                'db_table': 'lineas_articulos',
                'ordering': ['linea_id'],
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('marca_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('codigo_marca', models.CharField(max_length=14, unique=True)),
                ('marca_nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'marcas',
                'ordering': ['marca_id'],
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('promocion_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('limite', models.IntegerField(default=0)),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('bonificacion_unidades', models.IntegerField(blank=True, default=0, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'promocion',
            },
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('tipo_identificacion_id', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('tipo_identificacion_nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipoidentificacion',
            },
        ),
        migrations.CreateModel(
            name='TipoPedido',
            fields=[
                ('tipo_pedido_id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('tipo_pedido_nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipos_pedido',
                'ordering': ['tipo_pedido_id'],
            },
        ),
        migrations.CreateModel(
            name='TipoPromocion',
            fields=[
                ('tipo_promocion_id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('tipo_promocion_nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipos_promocion',
                'ordering': ['tipo_promocion_id'],
            },
        ),
        migrations.CreateModel(
            name='UnidadesMedida',
            fields=[
                ('unidad_medida_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('unidad_nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'unidades_medida',
                'ordering': ['unidad_medida_id'],
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('vendedor_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('vendedor_codigo', models.CharField(max_length=15, unique=True)),
                ('nro_documento', models.CharField(max_length=11)),
                ('nombres', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('correo_electronico', models.EmailField(max_length=255)),
                ('nro_movil', models.CharField(max_length=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.empresa')),
                ('tipo_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.tipoidentificacion')),
            ],
            options={
                'db_table': 'vendedor',
                'ordering': ['vendedor_id'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('sucursal_id', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('nombre_comercial', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.empresa')),
            ],
            options={
                'db_table': 'sucursal',
            },
        ),
        migrations.CreateModel(
            name='SublineasArticulos',
            fields=[
                ('sublinea_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('codigo_sublinea', models.CharField(max_length=15)),
                ('sublinea_descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.lineasarticulos')),
            ],
            options={
                'db_table': 'sublineas_articulos',
                'ordering': ['sublinea_id'],
            },
        ),
        migrations.CreateModel(
            name='PromocionArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promociones.articulos')),
                ('promocion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promociones.promocion')),
            ],
            options={
                'db_table': 'promocion_articulo',
            },
        ),
        migrations.AddField(
            model_name='promocion',
            name='articulo',
            field=models.ManyToManyField(through='promociones.PromocionArticulo', to='promociones.articulos'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='articulo_bonificado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promociones.articulosbonificado'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='canal_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.canalcliente'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='tipo_promocion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.tipopromocion'),
        ),
        migrations.CreateModel(
            name='NotaVenta',
            fields=[
                ('nota_venta_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nro_pedido', models.CharField(max_length=25)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('plazo', models.IntegerField()),
                ('tipo_documento', models.CharField(max_length=20)),
                ('total_pedido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.cliente')),
                ('condicion_venta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.condicionesventa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.empresa')),
                ('promocion_aplicada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promociones.promocion')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.sucursal')),
                ('tipo_pedido', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.tipopedido')),
            ],
            options={
                'db_table': 'notas_venta',
                'ordering': ['nota_venta_id'],
            },
        ),
        migrations.AddField(
            model_name='lineasarticulos',
            name='responsable_linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.vendedor'),
        ),
        migrations.CreateModel(
            name='ItemNotaVenta',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_item_bruto', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('factor_descuento', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('descuento_unitario', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total_item', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('es_bonificacion', models.BooleanField(default=False)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.articulos')),
                ('nota_venta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.notaventa')),
                ('promocion_aplicada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promociones.promocion')),
            ],
            options={
                'db_table': 'items_nota_venta',
                'ordering': ['item_id'],
            },
        ),
        migrations.AddField(
            model_name='gruposproveedor',
            name='responsable_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.vendedor'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.tipoidentificacion'),
        ),
        migrations.AddField(
            model_name='articulosbonificado',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.empresa'),
        ),
        migrations.AddField(
            model_name='articulosbonificado',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.gruposproveedor'),
        ),
        migrations.AddField(
            model_name='articulosbonificado',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.lineasarticulos'),
        ),
        migrations.AddField(
            model_name='articulosbonificado',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.marcas'),
        ),
        migrations.AddField(
            model_name='articulosbonificado',
            name='sublinea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.sublineasarticulos'),
        ),
        migrations.AddField(
            model_name='articulosbonificado',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.unidadesmedida'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.empresa'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.gruposproveedor'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.lineasarticulos'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.marcas'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='sublinea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.sublineasarticulos'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promociones.unidadesmedida'),
        ),
    ]
